API Remove Packagist API and use Composer to determine recommended andd latest updates
bringyourownideas/silverstripe-composer-update-checker pull request #28
Opened 2018-05-22 04:19 UTC by robbieaverill

High level changes:

* Removes Packagist API
* Adds Composer API (resolves https://github.com/bringyourownideas/silverstripe-composer-update-checker/issues/23)
* Uses Composer for all package, dependency, constraint and version manipulation handling (removes a bit of the BuildTask)
* Adds Composer API access to the ComposerLoader in the main maintenance module
* Adds "Available" (semver safe upgrade) and "Latest" (latest) columns to the main report (resolves https://github.com/bringyourownideas/silverstripe-composer-update-checker/issues/24)
* Moves some logic out of the BuildTask into UpdateChecker as a separate service class for easier mocking in tests

2018-05-22 11:19 UTC, spekulatius commented
Hello @robbieaverill 

thank you for working on this. I cloned the repo and had a look through your work. Looks all very good. The only thing I noticed were two missing doc blocks for private static arrays. Not sure if that is intentional - because it were the only two. Its in ComposerUpdateExtension and CheckComposerUpdatesTask, in case you want to add them. 

Cheers,
Peter

2018-05-22 11:26 UTC, robbieaverill commented
Thanks for the review! Ah yep, they were intentionally omitted as they get inherited this way from DataObject, but I’m happy to add them anyway if you’d prefer :-)

2018-05-22 12:20 UTC, spekulatius commented
Na, its fine. I was just wondering. Now I know :)

On Tue, 22 May 2018 at 18:26, Robbie Averill <notifications@github.com>
wrote:

> Thanks for the review! Ah yep, they were intentionally omitted as they get
> inherited this way from DataObject, but I’m happy to add them anyway if
> you’d prefer :-)
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/28#issuecomment-390956430>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AICvs7v0R1Mw2aD-0-AdQiRUeQlyeNKWks5t0_XcgaJpZM4UH9C9>
> .
>

2018-05-22 22:28 UTC, NightJar approved these changes
2 minor comments, but looks really good :)
Nice work!

2018-05-22 22:28 UTC, NightJar commented on src/Tasks/CheckComposerUpdatesTask.php
> +        return in_array($type, $allowedTypes);
Could this be cast to an array to catch the edge case where someone may set e.g. `allowed_types: silverstripe-vendormodule`?

2018-05-22 22:28 UTC, NightJar commented on src/Extensions/ComposerUpdateExtension.php
> +        'LatestHash' => 'Varchar(50)',
Defining some of these in a `private static $summary_fields` would be good, as a selection you wish to expose to CSV exported reports.

2018-05-23 01:48 UTC, NightJar commented on src/Extensions/ComposerUpdateExtension.php
> +        Injector::inst()->get(QueuedJobService::class)->queueJob($this->getJobName());
Oh, actually :s

```
[Recoverable Error] Argument 1 passed to QueuedJobService::queueJob() must be an instance of QueuedJob, string given
```
`silverstripe-composer-update-checker\src\Extensions\ComposerUpdateExtension.php on line 35`

queuedjobs `2.10.5`

2018-05-23 01:49 UTC, NightJar requested changes
The queued job instantiation requires an instance, not a string in the resolved version between this module and `silverstripe-maintenance`.

2018-05-23 03:59 UTC, robbieaverill commented
Updated. The test failures are unrelated and are caused by queuedjobs (although unrelated to that module too) - issue is here: https://github.com/silverstripe/silverstripe-framework/pull/8090

2018-05-23 22:45 UTC, merged

2018-05-23 22:45 UTC, NightJar commented
Thanks for explaining :)