Upgrading to SS4
bringyourownideas/silverstripe-composer-update-checker pull request #31
Opened 2018-06-04 23:04 UTC by ScopeyNZ

As titled.

2018-06-04 23:40 UTC, ScopeyNZ commented
Tests are passing on most platforms but I guess the combination of this module being memory intensive and generating a coverage report is making the 7.2 test fail - out of memory. Any suggestions?

2018-06-04 23:43 UTC, robbieaverill commented
Yep, you can bump the PHP memory limit in Travis: https://github.com/silverstripe/silverstripe-userforms/blob/master/.travis.yml#L22

We had a similar problem in framework yesterday

2018-06-05 05:15 UTC, robbieaverill requested changes
Looks good over all =)

2018-06-05 05:15 UTC, robbieaverill commented on tests/Extensions/ComposerUpdateExtensionTest.php
> -use SapphireTest;
`protected $requiredExtensions` will need to become `protected static $required_extensions` in this file

2018-06-05 05:15 UTC, robbieaverill commented on tests/Extensions/CheckComposerUpdatesExtensionTest.php
> +        // Register the extension stub for unit testing to avoid loading Composer
`setUp()` should be protected with PHPUnit 5

2018-06-05 05:15 UTC, robbieaverill commented on src/UpdateChecker.php
> +use SilverStripe\Core\Injector\Injector;
Can you phpcbf this?

2018-06-05 22:10 UTC, robbieaverill approved these changes

2018-06-05 22:10 UTC, robbieaverill commented
🎉

2018-06-05 22:32 UTC, merged