MNT Remove deprecated testing of protected method
bringyourownideas/silverstripe-composer-update-checker pull request #63
Opened 2022-04-27 01:52 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10294

2022-04-28 05:07 UTC, GuySartorelli requested changes
Bit of a simpler way of handling it - keeps the original logic of returning values based on the order in which the method is called (i.e. first time return false, second time return the mock package)

2022-04-28 05:07 UTC, GuySartorelli commented on tests/UpdateCheckerTest.php
> +        $this->updateChecker
```suggestion
        $this->updateChecker->expects($this->exactly(2))
```

2022-04-28 05:07 UTC, GuySartorelli commented on tests/UpdateCheckerTest.php
> +            }));
```suggestion
            ->willReturnOnConsecutiveCalls(
                false,
                $mockPackage,
            );
```

2022-04-28 05:07 UTC, GuySartorelli commented on tests/UpdateCheckerTest.php
> +use Composer\Package\PackageInterface;
```suggestion
```

2022-04-28 21:55 UTC, emteknetnz commented on tests/UpdateCheckerTest.php
> +            }));
updated

2022-04-28 21:55 UTC, emteknetnz commented on tests/UpdateCheckerTest.php
> +        $this->updateChecker
updated

2022-04-29 02:02 UTC, emteknetnz commented on tests/UpdateCheckerTest.php
> +use Composer\Package\PackageInterface;
Updated

2022-04-29 02:08 UTC, GuySartorelli approved these changes
Merge on green

2022-04-29 02:38 UTC, merged